CREATE DATABASE dbDevelopers;

CREATE TABLE developers(
   DEVELOPER_ID   INT               NOT NULL,
   NAME VARCHAR (100)     NOT NULL,
   EXPERIENCE  INT        NOT NULL,
  PRIMARY KEY (DEVELOPER_ID)
);

CREATE TABLE skills (
SKILL_ID INT NOT NULL ,
NAME VARCHAR (100) NOT NULL ,
PRIMARY KEY (SKILL_ID)
);

CREATE TABLE projects(
PROJECT_ID INT NOT NULL ,
NAME VARCHAR (100) NOT NULL ,
PRIMARY KEY (PROJECT_ID)
);

CREATE TABLE companies (
COMPANIE_ID INT NOT NULL ,
NAME VARCHAR (100) NOT NULL ,
PRIMARY KEY (COMPANIE_ID)
);

CREATE TABLE customers (
CUSTOMER_ID INT NOT NULL ,
NAME VARCHAR (100) NOT NULL,
PRIMARY KEY (CUSTOMER_ID)
);

CREATE TABLE developers_skills (
 DEVELOPER_ID int NOT NULL,
    SKILL_ID int NOT NULL,
    FOREIGN KEY (DEVELOPER_ID) REFERENCES developers(DEVELOPER_ID),
  FOREIGN KEY (SKILL_ID) REFERENCES skills(SKILL_ID)
);

CREATE TABLE projects_developers (
(
  PROJECT_ID   int NOT NULL,
  DEVELOPER_ID int NOT NULL,
  FOREIGN KEY (PROJECT_ID) REFERENCES projects (PROJECT_ID),
  FOREIGN KEY (DEVELOPER_ID) REFERENCES developers (DEVELOPER_ID)
);customers_projects


CREATE TABLE companies_projects(
COMPANIE_ID INT NOT NULL ,
PROJECT_ID INT NOT NULL ,
 FOREIGN KEY (COMPANIE_ID)  REFERENCES companies(COMPANIE_ID),
  FOREIGN KEY (PROJECT_ID) REFERENCES projects(PROJECT_ID)
);

CREATE TABLE customers_projects(
  CUSTOMER_ID INT NOT NULL ,
  PROJECT_ID INT NOT NULL ,
  FOREIGN KEY (CUSTOMER_ID)  REFERENCES customers(CUSTOMER_ID),
  FOREIGN KEY (PROJECT_ID) REFERENCES projects(PROJECT_ID)
);


